<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login for Rankings 2022</name>
   <tag></tag>
   <elementGuidId>5be3dcfb-a521-4ddb-aeb3-8194d102317b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-login.fw-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d242edbf-75d4-41d8-ae6a-57a87656db03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>079ca784-d36a-4f7b-94ca-4663b4dc942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-login fw-bold</value>
      <webElementGuid>679b02b6-c325-48f6-9d72-47bbfb39dcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login for Rankings 2022</value>
      <webElementGuid>f19f0545-9675-4fbf-ad4e-d3b993680e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-n-home-header[1]/div[@class=&quot;bg-white&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-white py-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;collapse navbar-collapse me-3&quot;]/ul[@class=&quot;navbar-nav ms-auto mb-2 mb-lg-0&quot;]/li[@class=&quot;nav-item me-2 ms-2&quot;]/button[@class=&quot;btn btn-login fw-bold&quot;]</value>
      <webElementGuid>55955ec9-d1b7-4276-b2e9-4a09c8b9a84c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>2ff8264b-2336-4d4e-8ef3-3fb0a66103aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::button[1]</value>
      <webElementGuid>41836333-f253-447e-81f9-88564ed78dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Municipal Budgets'])[1]/following::button[1]</value>
      <webElementGuid>b33956a5-9ee6-4ecf-8369-bed18a044cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login for 15th FC Grant'])[1]/preceding::button[1]</value>
      <webElementGuid>e91882c0-4735-45fc-9828-dc3ffe7b0116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[3]</value>
      <webElementGuid>e119b11d-d30f-4c7f-ac33-d29a89cef29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login for Rankings 2022']/parent::*</value>
      <webElementGuid>8d36ced1-e71d-4791-b2aa-61d0d16ac05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/button</value>
      <webElementGuid>e29e8c53-14da-4560-8023-be9f10a1b678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login for Rankings 2022' or . = 'Login for Rankings 2022')]</value>
      <webElementGuid>6efbec79-b8c2-4783-a83f-464c041ed76c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
