<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login for 15th FC Grant</name>
   <tag></tag>
   <elementGuidId>ba8932b0-286a-4733-90b9-89dad7931bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-login.fw-bold.btn-l-fc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17c4186e-4d0b-496b-99da-b9f6ce317084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42cf187a-4563-4375-aef2-6afa7dce00f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-login fw-bold btn-l-fc</value>
      <webElementGuid>6ac6733b-77a6-4bd0-9c01-48a70b41a653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login for 15th FC Grant</value>
      <webElementGuid>3f50a459-3f52-4f24-aacd-c62a9ba5772f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-n-home-header[1]/div[@class=&quot;bg-white&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-white py-0&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;collapse navbar-collapse me-3&quot;]/ul[@class=&quot;navbar-nav ms-auto mb-2 mb-lg-0&quot;]/li[@class=&quot;nav-item ms-1&quot;]/button[@class=&quot;btn btn-login fw-bold btn-l-fc&quot;]</value>
      <webElementGuid>d70b0bef-1423-471b-86fc-5a10ab33e923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>32376d8a-dfdc-43ad-a634-6a12da67a445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login for Rankings 2022'])[1]/following::button[1]</value>
      <webElementGuid>0744d255-cdea-48c6-9447-48f653bdf748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::button[2]</value>
      <webElementGuid>1e47c31e-c39f-49b8-a552-ef81cd477a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[2]</value>
      <webElementGuid>0855484f-5741-48a7-8e2e-e45672233b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National Financial Dashboard'])[1]/preceding::button[2]</value>
      <webElementGuid>51c599d4-d566-4a8b-80dc-d146c623dbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login for 15th FC Grant']/parent::*</value>
      <webElementGuid>2456c44b-5206-4105-9561-07cc094fa8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/button</value>
      <webElementGuid>bf6ce030-349d-4a47-9a31-285d839fd9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Login for 15th FC Grant' or . = 'Login for 15th FC Grant')]</value>
      <webElementGuid>e9364bdc-f76c-4f0d-a0a6-8c369bd4e165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
