<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password</name>
   <tag></tag>
   <elementGuidId>65b6c797-f844-4a63-923e-afcf9ac00190</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Census Code/ULB Code'])[1]/following::div[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c54-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>960372b3-2325-4b65-9bab-e29d1999e44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c54-2</value>
      <webElementGuid>fc5db83e-8275-42fc-bc35-078fd984b632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>8c01ace9-ca29-465a-981d-5365fe9138ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fc-grant&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;overall-container d-flex&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-6&quot;]/div[@class=&quot;bg-white card sign-in&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-body ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;forget-password&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c54-2 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c54-2&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c54-2&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c54-2&quot;]</value>
      <webElementGuid>d34d5d4c-9eb2-42a3-8cf1-c086e7c0e44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Census Code/ULB Code'])[1]/following::div[15]</value>
      <webElementGuid>54718fe2-1dc3-4a54-8621-b6487b310df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::div[26]</value>
      <webElementGuid>b1205bfb-1299-4c3c-8d47-310553aa5ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::div[5]</value>
      <webElementGuid>5fe0f887-fde2-4382-90b1-6d37da9968f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-form-field/div/div/div[3]</value>
      <webElementGuid>44bb5fe7-fbed-47b6-914b-4306ac02fa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password' or . = 'Password')]</value>
      <webElementGuid>7d252a19-aa55-4c71-b7e6-d3d65ec7c955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
