<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ULB</name>
   <tag></tag>
   <elementGuidId>7325ab71-96b5-4b6d-a5b9-29b1c5c43a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ulb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ulb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0449b5da-54d8-4255-b09d-5c0126cfa132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ulb</value>
      <webElementGuid>491d6a60-a96c-4419-b352-54bb66ea09eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>1735b3d7-0638-45f4-ba9c-045cfc6b6c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ULB </value>
      <webElementGuid>9634bf57-6a47-4873-bf6d-e19ddb3aaa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulb&quot;)</value>
      <webElementGuid>13318aa2-2252-4429-9470-cfaeb5712488</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ulb']</value>
      <webElementGuid>9c0a277c-0322-4d5d-8a2a-65e44ed5fd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::div[5]</value>
      <webElementGuid>5d1951f7-9728-4c28-887f-7bf512be9d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STATE'])[1]/preceding::div[1]</value>
      <webElementGuid>1dd8d081-bfd2-4968-9684-fe491c150326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MoHUA'])[1]/preceding::div[3]</value>
      <webElementGuid>bfb25b6e-2256-44d3-8320-d681f8fd636a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ULB']/parent::*</value>
      <webElementGuid>214f2d1f-48c8-460c-a7e4-f730e827b287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-user-type-confirmation/div/div/div/div/div</value>
      <webElementGuid>719a4420-a85f-452b-b09a-77c648b9b423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ulb' and (text() = ' ULB ' or . = ' ULB ')]</value>
      <webElementGuid>b29d0814-3678-4d93-9eeb-bb27429acabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
