<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select File</name>
   <tag></tag>
   <elementGuidId>16b0a750-8b14-4ea4-aba6-9b33a19c88ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cdk-step-content-0-3&quot;]/div/div[1]/div/div/div[2]/div/div/div[2]/div[2]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29842be6-9026-406d-8785-14c3d8ed75c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-12 mb-3 ng-star-inserted</value>
      <webElementGuid>a7448d9a-1e48-45f6-9821-6bd1686c81aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select File </value>
      <webElementGuid>04cd5218-7b1d-4897-ab59-6be04fbd1841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-3&quot;)/div[@class=&quot;container mt-4 w-80 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row mx-auto&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;card card-form mb-4 com-style ng-star-inserted&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;loop&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 com-style ng-star-inserted&quot;]/div[@class=&quot;row ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;col-sm-12 mb-3 ng-star-inserted&quot;]</value>
      <webElementGuid>9cb6453a-0001-4348-97a4-90394490b437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-3']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>3552e42f-c7e0-4842-8cc9-a487865886d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2022-23'])[1]/following::div[1]</value>
      <webElementGuid>2c3b3256-6c09-4064-b874-4acfa5335817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[211]/following::div[4]</value>
      <webElementGuid>be2958db-b4a1-42b7-aca2-1c8761394df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>1d218ae6-3e39-4493-a473-067220fdca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Select File ' or . = ' Select File ')]</value>
      <webElementGuid>d1f0d51d-da2a-4cbe-99b0-3e9946ca0b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-3']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div[2]/button/div/div</value>
      <webElementGuid>01536f64-f209-44c1-9b99-1e997f055e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2022-23'])[1]/following::div[3]</value>
      <webElementGuid>6d42337d-d33e-4d7b-b7ad-5102d61bc416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2021-22'])[1]/preceding::div[5]</value>
      <webElementGuid>87e1b8c3-d779-4865-b199-34b155fb99bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button/div/div</value>
      <webElementGuid>82a8f763-3e8c-466c-b020-192b49821de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-3']/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/button/div/div</value>
      <webElementGuid>061fa970-3849-4e3f-8764-b6a265d875e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2023-24'])[1]/following::div[3]</value>
      <webElementGuid>2fd06920-45bf-427b-ad69-0663370bba67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[71]/following::div[7]</value>
      <webElementGuid>2ae8b08b-e809-4de9-9e3d-717bc8e5d8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2022-23'])[1]/preceding::div[4]</value>
      <webElementGuid>76ea93d1-dc93-4934-ad02-4af4ce7b0f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select File']/parent::*</value>
      <webElementGuid>7be661e4-e7d4-4ab5-b97b-2fc7481499b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div</value>
      <webElementGuid>9f94cbf9-8206-485d-ad73-f8ffd370f5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
