<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target Indicator 2023-24_ny8all</name>
   <tag></tag>
   <elementGuidId>a5428a32-dd14-41bb-8058-c36165a6e08b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4.003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7802e617-fff6-4054-888a-488e54fed963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1b733ab3-756d-498f-9150-1c5c9a14c931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onwheel</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>6743c974-b5ee-450c-bcb2-d4af794ed841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9ce8c42d-7f31-4982-a0a2-dea2b8ebf1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0-100</value>
      <webElementGuid>089c8062-d985-40a3-9839-ec21fb9151e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4.003</value>
      <webElementGuid>0368ec22-3b4d-4f8a-8e40-5796075ef0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ny8all</value>
      <webElementGuid>f52ea3f5-2c4d-44a4-9307-6904064b4be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ny8all</value>
      <webElementGuid>9454ab6b-a621-4fae-9baf-a205c864d7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-3&quot;]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-ulb-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/app-twenty-eight-slb[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;my-3 ng-star-inserted&quot;]/app-web-form[1]/mat-card[@class=&quot;custom-shadow dur ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-sm-6 col-sm-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-3 ng-star-inserted&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;common-font-family col-12 d-flex align-items-baseline ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex&quot;]/input[@id=&quot;4.003&quot;]</value>
      <webElementGuid>ba9cd66e-069c-4cb2-985f-8741588615d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4.003']</value>
      <webElementGuid>0aa12924-11cb-48d5-83d2-2f097b82772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr/td[3]/div/div/div/input</value>
      <webElementGuid>074da7f1-1fc7-4101-9a43-5a69b3d7d107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0-100' and @id = '4.003' and @name = 'ny8all']</value>
      <webElementGuid>6f7b6368-9a59-4c4b-85b4-08a73e3e03a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
