<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target Indicator 2023-24_ixkw1j</name>
   <tag></tag>
   <elementGuidId>9eb66cb6-9e59-4829-941a-a39d7cbc9958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='3.003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>920e7daf-de2c-4efa-a383-0c8574046496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5821670f-6f35-4e69-b88b-248f0b236118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onwheel</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>782b8e80-d43d-4c14-a2da-902e50d1b5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cbb05c4c-51da-4773-aa87-0f5cece64d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0-100</value>
      <webElementGuid>040788be-245e-470a-bc46-4bb5e15a5835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3.003</value>
      <webElementGuid>7ba81694-ed12-4c89-baa8-216b6971d0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ixkw1j</value>
      <webElementGuid>32ea4890-6394-4c1f-85b9-34f00f9c4320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>ixkw1j</value>
      <webElementGuid>f67d2f6b-ad11-44f7-bd19-e3c7f253674b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-3&quot;]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-ulb-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/app-twenty-eight-slb[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;my-3 ng-star-inserted&quot;]/app-web-form[1]/mat-card[@class=&quot;custom-shadow dur ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-sm-6 col-sm-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-3 ng-star-inserted&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;common-font-family col-12 d-flex align-items-baseline ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex&quot;]/input[@id=&quot;3.003&quot;]</value>
      <webElementGuid>21c9683a-59e1-4947-92ce-a37b547126c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='3.003']</value>
      <webElementGuid>a43e9cfc-f866-48a3-a846-f1bb4aa5635a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr/td[3]/div/div/div/input</value>
      <webElementGuid>cd44ac97-92c9-4c55-b94b-99a4695ec444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0-100' and @id = '3.003' and @name = 'ixkw1j']</value>
      <webElementGuid>f56eda5c-79e4-4938-9d10-2973e9f89692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
