<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target Indicator 2023-24_4.003</name>
   <tag></tag>
   <elementGuidId>c9ade890-4813-4ffa-84b0-44ef56ca9bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='4.003']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d265194-23db-49a5-a8d2-11ab5b534b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7b0fbc10-f260-4ea7-8244-b6a8685f9868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onwheel</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>50817431-2bb7-4240-9cf2-c861fd38d0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>80dc32c2-b627-4e1a-ba27-3a0154d41930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0-100</value>
      <webElementGuid>44778a78-746a-4c24-8d5c-35cf0aa25dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4.003</value>
      <webElementGuid>60e1b1d7-89c6-4c3c-a9dd-401e0468442b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-3&quot;]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-ulb-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/app-twenty-eight-slb[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;my-3 ng-star-inserted&quot;]/app-web-form[1]/mat-card[@class=&quot;custom-shadow dur ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-sm-6 col-sm-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-3 ng-star-inserted&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;common-font-family col-12 d-flex align-items-baseline ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex&quot;]/input[@id=&quot;4.003&quot;]</value>
      <webElementGuid>49fa3113-cfe5-42ee-a0b9-697fada546d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='4.003']</value>
      <webElementGuid>e933d795-f711-421f-a0cb-5a5b60acaec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr/td[3]/div/div/div/input</value>
      <webElementGuid>dd3ab495-c45a-4524-a865-2f3e3b2c3ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0-100' and @id = '4.003']</value>
      <webElementGuid>e7d7e831-9a5b-44c4-82bd-de9d7e984d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
