<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target Indicator 2023-24_3.002</name>
   <tag></tag>
   <elementGuidId>338b6889-65ce-431f-bb54-1f77c70b8d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='3.002'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21fda09a-dc66-4e7e-8be8-a4c5175cb463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2207ed7a-c2dd-4483-8a73-99785c715ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onwheel</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>d10102a4-4dda-4d6d-bfe5-b08973165c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b7601c37-445f-4023-84c2-d5117606a9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0-100</value>
      <webElementGuid>f6c69cf2-1241-40c2-88bd-d18dd1ff36f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3.002</value>
      <webElementGuid>d2591cf7-d1cd-4b60-bbb7-3a8b1bc54bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-3&quot;]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-ulb-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/app-twenty-eight-slb[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;my-3 ng-star-inserted&quot;]/app-web-form[1]/mat-card[@class=&quot;custom-shadow dur ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-sm-6 col-sm-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-3 ng-star-inserted&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;common-font-family col-12 d-flex align-items-baseline ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex&quot;]/input[@id=&quot;3.002&quot;]</value>
      <webElementGuid>9ce4f2c0-7643-4057-8dba-28a63eb792f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='3.002'])[2]</value>
      <webElementGuid>7a92af3e-c972-4b72-a0c5-bc6a0b7c4943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr[2]/td[2]/div/div/div/input</value>
      <webElementGuid>a45b45e0-7343-4eaf-9a9b-108fa4ca3510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0-100' and @id = '3.002']</value>
      <webElementGuid>c3ba4f12-b405-428a-8b9a-f805106aa1eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
