<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_XV-FC recommended Urban Local Body Fi_7e1991</name>
   <tag></tag>
   <elementGuidId>15e5c9fb-a854-406e-9580-7e5f6dea04b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='LOGIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4eef05b6-c5e6-4c1b-9f3d-6914a618d43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>475cfdb8-b16a-4ba3-91f8-8742e7e4599c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>0a38b5ff-adc4-450d-937f-152f338a5d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>4cc92afb-384e-41ba-a86e-c86cfde8d13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-fc-grant[1]/div[@class=&quot;fc-grant-2&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center align-items-center&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-6 col-lg-6 text-center image-side&quot;]/div[1]/input[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>9f5c121d-84a7-459d-abf6-f5c00b3b0dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>searchIcon</value>
      <webElementGuid>86060b67-fc4b-4b06-b03e-0391f4d90c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>c813cdf8-ae40-4778-8796-32b12bdcc582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='LOGIN']</value>
      <webElementGuid>6eb98b4b-40c2-4f7c-ac2c-3755c37acb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f35e3916-bc9e-48d0-abe6-1a8cf32e11e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>2dc58f9f-86bc-4e85-9fb5-342b01cbaaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>08339e68-5fb7-44ee-976c-7e176fd7b15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>d9b95752-9000-4869-8c1d-85b2f1b8ad03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
