<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Target Indicator 2023-24_4.003_1</name>
   <tag></tag>
   <elementGuidId>bcdf7c04-2298-46c5-a765-36f431cb4ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='4.003'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97b1bc75-4624-431c-ba73-6c5811ed16ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9e95d790-63ed-4492-b687-d3bdd9bf0713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onwheel</name>
      <type>Main</type>
      <value>this.blur()</value>
      <webElementGuid>514a1e21-551f-460f-888f-b1fc7752c81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f9b648c-21d7-4449-b3fb-198b893e3720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0-9999</value>
      <webElementGuid>705356db-dfbc-4b80-9184-8854e35066e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4.003</value>
      <webElementGuid>1e5ec188-620c-49c0-9403-7bfa137edab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-tns-0-3&quot;]/app-root[1]/div[@class=&quot;wrapper app-wrapper&quot;]/app-ulb-form[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/app-twenty-eight-slb[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;my-3 ng-star-inserted&quot;]/app-web-form[1]/mat-card[@class=&quot;custom-shadow dur ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;col-sm-6 col-sm-12&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mt-3 ng-star-inserted&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;common-font-family col-12 d-flex align-items-baseline ng-star-inserted&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;d-flex&quot;]/input[@id=&quot;4.003&quot;]</value>
      <webElementGuid>3195ac50-9059-468f-bf16-e8e97ebd4cb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='4.003'])[2]</value>
      <webElementGuid>c6e25283-80fb-4e88-b491-814445665ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr[2]/td[3]/div/div/div/input</value>
      <webElementGuid>69abe7f9-2314-4e45-8362-99f50343c828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @placeholder = '0-9999' and @id = '4.003']</value>
      <webElementGuid>9aebbe3a-53e9-4b1a-a15c-49a1e04a8445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
