<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-option_Non ODF</name>
   <tag></tag>
   <elementGuidId>2bb86ac8-dd95-4494-812a-8155f125c9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-option</value>
      <webElementGuid>735851d8-a5e0-4a4a-857d-c0251f81b6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>180e1d8d-f21f-4bc0-bcb8-936cf7388fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option mat-focus-indicator mat-tooltip-trigger mb-2 ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>9259a814-04e2-4d9c-9f68-aa396afbc7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-option-3</value>
      <webElementGuid>ad55e6a1-8e2b-41c7-898e-0fa01a3bf499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>14cfef29-3ebb-45df-82ac-d37ecfec828d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a86c942-a2de-47df-87c4-7661d9aca5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-3</value>
      <webElementGuid>6ce3c70d-2bf4-4bf7-a6e2-2af6c8f15c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Non ODF</value>
      <webElementGuid>2b5bdbf9-1c95-46a3-a3e4-c8c73e378807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-3&quot;)</value>
      <webElementGuid>21a904d4-3474-4614-8e52-c042fed89aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-3']</value>
      <webElementGuid>f9faab45-d405-4b86-8439-82c164d0d0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1-panel']/div[2]/mat-option[4]</value>
      <webElementGuid>03ca5082-cc43-4cd5-ad0c-10eb82d591d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ODF'])[1]/following::mat-option[1]</value>
      <webElementGuid>fa535d23-303b-41d8-88a6-21177d3b7b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ODF+'])[1]/following::mat-option[2]</value>
      <webElementGuid>ef4dfe12-9075-45bb-9321-750c5f157f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Rating'])[1]/preceding::mat-option[1]</value>
      <webElementGuid>4e94545f-fd3c-48be-98ca-ab9451246f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[4]</value>
      <webElementGuid>5ad4b316-0f7d-4de9-902d-e91af3c0eb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-option[@id = 'mat-option-3' and (text() = 'Non ODF' or . = 'Non ODF')]</value>
      <webElementGuid>f3f456ab-1348-4b91-b3ed-aa9ef9bc7235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
