<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ODF</name>
   <tag></tag>
   <elementGuidId>ca1916b7-3030-4b1e-ad4e-4b7fbe8f2f2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-2']/span/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-2 > span.mat-option-text > div.d-flex.flex-column.mt-2 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40447cca-157f-4de6-a9c1-8a6deaba656c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ODF</value>
      <webElementGuid>ec80ea24-dc0d-43c7-b920-73caae17a11c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-2&quot;)/span[@class=&quot;mat-option-text&quot;]/div[@class=&quot;d-flex flex-column mt-2&quot;]/span[1]</value>
      <webElementGuid>ed9ac1a6-a0a8-4cd1-90b7-d09cba5e8376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-2']/span/div/span</value>
      <webElementGuid>97ba3b65-92f9-42ab-b385-2402316e62b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ODF+'])[1]/following::span[2]</value>
      <webElementGuid>762f9131-2b93-4f23-80f7-a1630d6843a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ODF++'])[1]/following::span[4]</value>
      <webElementGuid>f33dabd4-5b88-4b91-b966-849288492de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non ODF'])[1]/preceding::span[1]</value>
      <webElementGuid>5879f31b-7535-4ecd-9589-0776b086e371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Rating'])[1]/preceding::span[3]</value>
      <webElementGuid>9740afc9-d070-4b1a-a739-3b37ea70c5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ODF']/parent::*</value>
      <webElementGuid>08d1bf92-e951-4998-bd01-4b1dc5a1e40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span/div/span</value>
      <webElementGuid>731a1902-55db-4c1e-8680-0a2455ad9899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ODF' or . = 'ODF')]</value>
      <webElementGuid>1ecf7fe6-84b4-4cc2-a375-9ffacf7cbd3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
