<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Skilling and Employment Program_Login_481774</name>
   <tag></tag>
   <elementGuidId>c3c9b199-c2a2-4baf-a930-615b2a2d479d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='myPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f8fc5c-d4fe-41f2-8dce-9be823b9b62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a8a484fb-8ea4-44b1-86ce-69cc2a2ee038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myPassword</value>
      <webElementGuid>ee95f82c-8806-4344-ae1f-e45e6f444c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>db0a4428-82cb-4b9a-ab24-70a70ccd2532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LoginForm[password]</value>
      <webElementGuid>fd86960c-a1a2-47b9-8cf6-e22e1f94fa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>755158df-e4b5-401e-9283-0fc7543e1e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>9a0a5434-c3a1-4a02-a70f-8e2706d99885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onselectstart</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>5a7cc43f-3d9e-43ec-b739-15776c753fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>470d08bc-7bcd-4c17-85df-a6d6fa9ecfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncopy</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>7617fdf3-7515-4873-a574-a65ef87a6eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncut</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>f28f5c7a-6d2e-498a-ab19-feef72f66f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrag</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>702edbb8-0916-490d-a177-e6c5b1e431b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>1fd3704a-aea2-428f-929d-2e20bff03ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d75c446-eabf-4a53-8f0d-e71e33b13d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myPassword&quot;)</value>
      <webElementGuid>aac3f6d0-18b5-4b42-b194-9fdd4f0ed8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myPassword']</value>
      <webElementGuid>cef8598e-0248-432c-a259-69e0127171b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[2]/input</value>
      <webElementGuid>455959b7-0252-4bd7-a8c1-0cfc00d270c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a9566b4d-54fc-420e-b66a-6268a43f9ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'myPassword' and @name = 'LoginForm[password]' and @placeholder = 'Password']</value>
      <webElementGuid>29fca5c5-355b-481a-ae44-cda6d7aa897d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
