<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date_ComplianceFrequencystart_date</name>
   <tag></tag>
   <elementGuidId>01ab85c6-4d78-4112-8f8b-0a1a035625e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textbox_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textbox_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2deb7098-af21-4de7-b593-a38dc8a29a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0f7d3d4-7450-4fa7-8916-d9c24ab1e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textbox_id</value>
      <webElementGuid>d507b4f0-66bd-4058-88c3-e2c23706d5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>61908e0e-6773-43e5-8be3-d49832feaa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ComplianceFrequency[start_date]</value>
      <webElementGuid>b6393316-eb2a-45f3-ba01-65a6eb9bc1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select start date</value>
      <webElementGuid>99735dae-575f-4e5e-842f-c1cd00d39b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4422d80b-2c40-4b6c-8de9-325b20ea6ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4bdf2ed0-c603-45ce-bf6b-fafb38f8c8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datetimepicker-source</name>
      <type>Main</type>
      <value>textbox_id-datetime</value>
      <webElementGuid>6e350be1-1bae-4ff5-9527-0aa2a094cf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datetimepicker-type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7cdafd24-a195-4c05-a159-8fc3cef0738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-datetimepicker</name>
      <type>Main</type>
      <value>datetimepicker_c5d87b35</value>
      <webElementGuid>61750280-3c6d-40a5-9fe5-cc533a5eba6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textbox_id&quot;)</value>
      <webElementGuid>897122fe-81bb-4b2d-b31f-395794da764b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textbox_id']</value>
      <webElementGuid>54016d88-f443-472b-97ca-c60174b54566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textbox_id-datetime']/input</value>
      <webElementGuid>31672c0c-3e6c-42e6-b5e3-b1afca2048d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>a45d299e-134e-44ba-9ff1-9834a7e85eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'textbox_id' and @name = 'ComplianceFrequency[start_date]' and @placeholder = 'Select start date']</value>
      <webElementGuid>add39a0e-a676-4f51-9ea9-0a9691da421b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
