<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Narration_ComplianceFrequencynarration</name>
   <tag></tag>
   <elementGuidId>2b40684c-334e-4c7b-9015-345cc4dac3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#compliancefrequency-narration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='compliancefrequency-narration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3344b9db-d725-485b-a479-e512b596869c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09739ada-95f6-4463-af2f-4fa756fd926d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>compliancefrequency-narration</value>
      <webElementGuid>b927ece0-855e-4fff-b2f9-0676593ee184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>694da7eb-b11a-4272-9cd0-d41888ab1385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ComplianceFrequency[narration]</value>
      <webElementGuid>3eea22c3-ff9b-4253-a8fd-77812887965c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;compliancefrequency-narration&quot;)</value>
      <webElementGuid>6ce2c158-ab54-4bd8-bfdf-07918e204fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='compliancefrequency-narration']</value>
      <webElementGuid>76937ab6-9b0c-48b6-938b-c930f847bff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[9]/div/input</value>
      <webElementGuid>3399c124-0552-4fa3-9bc4-8f8680aeb365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>73cf319c-be4e-4080-82ed-0798cb2974ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'compliancefrequency-narration' and @name = 'ComplianceFrequency[narration]']</value>
      <webElementGuid>b06bf17c-7f8b-4c15-ac4f-42faf2d38bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
