<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dead line_ComplianceFrequencydead_line_date</name>
   <tag></tag>
   <elementGuidId>4ebdc7b6-96ab-42d4-a9da-9bb8ac913edb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textboxes_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textboxes_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2725f8b-17a0-4dc3-925c-82dd44d2f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6b1fb22-ce08-4e40-90d7-5ecee0896c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textboxes_id</value>
      <webElementGuid>72c97efc-527a-4aeb-bbd2-5db32da676ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1c4cd6b2-1666-4f68-bf1c-f55e5d3708c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ComplianceFrequency[dead_line_date]</value>
      <webElementGuid>c21da9fd-3817-45c1-8c47-ed644ee361e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Dead line</value>
      <webElementGuid>dac12615-fbf4-4227-9ea0-db1e174910f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b225b653-c3a2-4c61-a3be-510176e70307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datetimepicker-source</name>
      <type>Main</type>
      <value>textboxes_id-datetime</value>
      <webElementGuid>c19a9982-7c15-4b7c-8fe8-0f6220ae553b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-datetimepicker-type</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>29e557ec-e815-441f-ba1b-6c4653e62dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-krajee-datetimepicker</name>
      <type>Main</type>
      <value>datetimepicker_c5d87b35</value>
      <webElementGuid>6e6359da-07b5-4a50-83fc-99cc45f52839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textboxes_id&quot;)</value>
      <webElementGuid>ec5a7e6e-a85e-4090-afc9-6c74703f559d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textboxes_id']</value>
      <webElementGuid>86a84025-6fca-4a67-9839-a8696dd8ac4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='textboxes_id-datetime']/input</value>
      <webElementGuid>10f1d121-47f5-4ef6-83f4-8df62216348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>660590bf-6156-4a5c-8607-bcc3b628b593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'textboxes_id' and @name = 'ComplianceFrequency[dead_line_date]' and @placeholder = 'Select Dead line']</value>
      <webElementGuid>279284f8-3629-4ae4-a830-4842cd351506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
