<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alert_ComplianceFrequencyalert</name>
   <tag></tag>
   <elementGuidId>391c9621-9541-43de-b6e2-d90f630c9e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#compliancefrequency-alert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='compliancefrequency-alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e67a5eee-c064-47c4-bbc4-312fbb5f7dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1388ac1f-95d7-4a23-9561-5c8519067d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>compliancefrequency-alert</value>
      <webElementGuid>d027830e-090f-43d0-8968-ad67394bf3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e0c8e6e3-0bc7-421f-afb1-1dd1f05fc567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ComplianceFrequency[alert]</value>
      <webElementGuid>976d6295-aa48-4973-993f-f23d49cb53d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bde9fae1-709f-4ab8-8952-edbfefb3b83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;compliancefrequency-alert&quot;)</value>
      <webElementGuid>0f8af0c7-3de7-4353-ad68-d237c59d767c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='compliancefrequency-alert']</value>
      <webElementGuid>8e0ddadd-16b3-43f1-821d-06d4f5f296ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/div[8]/div/input</value>
      <webElementGuid>a453f0f7-0ffe-49a0-b19b-9c062a648347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>5d6297ee-559c-45ec-b35a-d9f334e3f335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'compliancefrequency-alert' and @name = 'ComplianceFrequency[alert]']</value>
      <webElementGuid>ba6bfed7-cac9-45ee-b00a-8dc9cef307a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
