<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select multiple items</name>
   <tag></tag>
   <elementGuidId>77e28370-154f-4b2c-bbb0-ebaace64b312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection__placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-compliancefrequency-fpo_id-container']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35164c07-716d-421e-97f2-7ec7673914f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>c2074dbf-71df-4c42-ac4e-9d8ba87ea901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select multiple items</value>
      <webElementGuid>df0f2e20-4e90-4f4a-bb32-fe76eab4aa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-compliancefrequency-fpo_id-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>12e0f6ec-65f9-4eee-a574-b4a5e04e10dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-compliancefrequency-fpo_id-container']/span</value>
      <webElementGuid>181776c5-ad6a-44b9-852d-92f67735d850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FPO'])[3]/following::span[5]</value>
      <webElementGuid>92c88e20-2fed-4241-8403-5a7cf2fc28d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Level'])[1]/following::span[5]</value>
      <webElementGuid>269670bb-bee7-406e-aef8-0b0fb0ba9368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[2]/preceding::span[3]</value>
      <webElementGuid>3c44c6fd-b81e-487d-a8a2-145b269b2c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start date'])[1]/preceding::span[3]</value>
      <webElementGuid>c085c8f1-0e54-462b-b793-9dd51c88ea23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select multiple items']/parent::*</value>
      <webElementGuid>b52bd9f6-7967-4ae6-b76f-d7082178cef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>bceb1d95-bf0f-4e90-93d3-a4f1fca62693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select multiple items' or . = 'Select multiple items')]</value>
      <webElementGuid>c0e9e4e0-25bb-4818-b76c-a5a44d3563ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
