<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Filefour</name>
   <tag></tag>
   <elementGuidId>b277c4bc-8a33-486d-bc49-62d19f36a844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;cdk-step-content-0-3&quot;]/div/div[1]/div/div/div[2]/div/div/div[2]/div[4]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b20b7c69-54c2-4886-9cac-8775003b92e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-6 file-text</value>
      <webElementGuid>871634b5-8a7a-4ffe-a029-22429df58155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select File </value>
      <webElementGuid>c82b73f3-f119-4926-9d78-6ed11cd6baeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-3&quot;)/div[@class=&quot;container mt-4 w-80 ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row mx-auto&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;card card-form mb-4 com-style ng-star-inserted&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;loop&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3 com-style ng-star-inserted&quot;]/div[@class=&quot;row ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;col-sm-12 mb-3 ng-star-inserted&quot;]/button[@class=&quot;btn form-btn com-style w-100 test-city&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 file-text&quot;]</value>
      <webElementGuid>559fa228-bce1-4cfb-a576-e758e20c31c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-3']/div/div/div/div/div[2]/div/div/div[2]/div[4]/div/div[2]/button/div/div</value>
      <webElementGuid>95a8be15-6cf9-448c-a548-cae2266504e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2020-21'])[1]/following::div[3]</value>
      <webElementGuid>0ce50034-2953-43aa-8940-39c736277868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button/div/div</value>
      <webElementGuid>3e811279-8d29-4bf7-9bf2-b0c812f704c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Select File ' or . = ' Select File ')]</value>
      <webElementGuid>7c50cdae-4977-43ee-82eb-dc6ee4f58cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
